name = "moscow-weather-bot"
main = "src/worker.js"
compatibility_date = "2026-04-10"
workers_dev = true

[[durable_objects.bindings]]
name = "BOT_STATE"
class_name = "BotStorage"

[[migrations]]
tag = "v1"
new_classes = ["BotStorage"]

[observability]
enabled = true
